class ClientPropertyRelationshipService {
  constructor({clientRepository,propertyRepository,unitRepository,relationshipRepository,transaction,authorize=ClientPropertyRelationshipService.defaultAuthorize}={}) {
    if(!clientRepository||!propertyRepository||!unitRepository||!relationshipRepository||!transaction)throw new Error("client, property, unit, relationship repositories and transaction are required");
    this.clientRepository=clientRepository;this.propertyRepository=propertyRepository;this.unitRepository=unitRepository;this.relationshipRepository=relationshipRepository;this.transaction=transaction;this.authorize=authorize;
  }
  async createProperty({principal,...property}){this.#authorize(principal,"property:create");return this.transaction(principal,"property.create",db=>this.propertyRepository.create({principal,property,db}));}
  async createUnit({principal,...unit}){this.#authorize(principal,"unit:create");return this.transaction(principal,"unit.create",async db=>{if(!await this.propertyRepository.get({principal,propertyId:unit.propertyId,db}))throw new Error("Property not found");return this.unitRepository.create({principal,unit,db});});}
  async createRelationship({principal,...relationship}){this.#authorize(principal,"clientPropertyRelationship:create");return this.transaction(principal,"client-property-relationship.create",async db=>{if(!await this.clientRepository.get({principal,clientId:relationship.clientId,db}))throw new Error("Client not found");if(!await this.propertyRepository.get({principal,propertyId:relationship.propertyId,db}))throw new Error("Property not found");if(relationship.unitId){const unit=await this.unitRepository.get({principal,unitId:relationship.unitId,db});if(!unit||unit.propertyId!==relationship.propertyId)throw new Error("Unit not found for property");}return this.relationshipRepository.create({principal,relationship,db});});}
  async closeRelationship({principal,relationshipId,endAt}){this.#authorize(principal,"clientPropertyRelationship:update");return this.transaction(principal,"client-property-relationship.close",db=>this.relationshipRepository.close({principal,relationshipId,endAt,db}));}
  async listClientRelationships({principal,clientId}){this.#authorize(principal,"clientPropertyRelationship:read");return this.transaction(principal,"client-property-relationship.list-client",db=>this.relationshipRepository.listByClient({principal,clientId,db}));}
  async listPropertyRelationships({principal,propertyId,unitId=null}){this.#authorize(principal,"clientPropertyRelationship:read");return this.transaction(principal,"client-property-relationship.list-property",db=>this.relationshipRepository.listByProperty({principal,propertyId,unitId,db}));}
  #authorize(principal,action){if(!principal?.userId||!principal?.organizationId)throw new Error("Trusted principal is required");if(!this.authorize(principal,action,principal.organizationId)){const e=new Error("Not authorized");e.statusCode=403;throw e;}}
  static defaultAuthorize(principal,action,organizationId){return principal.organizationId===organizationId&&Array.isArray(principal.permissions)&&principal.permissions.includes(action);}
}
module.exports={ClientPropertyRelationshipService};
